---
name: Codeowners

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validate:
    if: github.event.repository.fork == false
    name: Validate CODEOWNERS
    uses: buluma/GitHub-Actions/.github/workflows/codeowners.yaml@master
