---
name: Docker Build DevOps Bash Tools (Debian)

on:
  push:
    branches:
      - master
      - main
    paths:
      - devops-bash-tools-debian/**
      - src/**
      - .github/workflows/docker_build_devops_bash_tools_debian.yaml
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  docker_build:
    name: Docker Build
    uses: buluma/GitHub-Actions/.github/workflows/docker_build.yaml@master
    with:
      repo: buluma/bash-tools
      tags: debian
      context: devops-bash-tools-debian
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
