#
#  Author: Hari Sekhon
#  Date: 2022-01-27 18:55:16 +0000 (Thu, 27 Jan 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Docker Build DevOps Bash Tools (Fedora)

on:
  push:
    branches:
      - master
      - main
    paths:
      - devops-bash-tools-fedora/**
      - src/**
      - .github/workflows/docker_build_devops_bash_tools_fedora.yaml
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  docker_build:
    name: Docker Build
    uses: HariSekhon/GitHub-Actions/.github/workflows/docker_build.yaml@master
    with:
      repo: harisekhon/bash-tools
      tags: fedora
      context: devops-bash-tools-fedora
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
