---
name: Docker Build DevOps Perl Tools (Ubuntu)

on:
  push:
    branches:
      - master
      - main
    paths:
      - devops-perl-tools-ubuntu/**
      - src/**
      - .github/workflows/docker_build_devops_perl_tools_ubuntu.yaml
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  docker_build:
    name: Docker Build
    uses: buluma/GitHub-Actions/.github/workflows/docker_build.yaml@master
    with:
      repo: buluma/perl-tools
      tags: ubuntu latest
      context: devops-perl-tools-ubuntu
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
