---
name: Fork Update PR

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    # fork-sync happens for default branch every hour, so just after that, run PRs for branches
    - cron: '2 10 * * 2'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  fork_update_pr:
    if: github.repository_owner != 'buluma'
    name: Fork Update PR
    uses: buluma/GitHub-Actions/.github/workflows/fork-update-pr.yaml@master
    with:
      debug: ${{ github.event.inputs.debug || false }}
