---
name: Fork Sync

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  fork_sync:
    if: github.repository_owner != 'buluma'
    name: Fork Sync
    uses: buluma/GitHub-Actions/.github/workflows/fork-sync.yaml@master
    with:
      debug: ${{ github.event.inputs.debug || false }}
