---
name: JSON

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

jobs:
  check_json:
    if: github.event.repository.fork == false
    name: Check JSON
    uses: buluma/GitHub-Actions/.github/workflows/json.yaml@master
