# ============================================================================ #
#                  S e m g r e p   C l o u d   W o r k f l o w
# ============================================================================ #

# Logs results to https://semgrep.dev/

---
name: Semgrep Cloud

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  semgrep:
    if: github.event.repository.fork == false
    name: Semgrep Cloud
    uses: buluma/GitHub-Actions/.github/workflows/semgrep-cloud.yaml@master
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
